development: #https://arc.net/l/quote/ghrtjtis to access it in active job
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: hangin_production
  ssl_params: { verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %> } #https://stackoverflow.com/questions/47635016/connect-to-aws-elasticache-with-in-transit-encryption && https://arc.net/l/quote/iipecgab
